databases:
  - name: multichain-db
    databaseName: multichain_db
    user: multichain_user
    plan: free

services:
  - type: web
    name: multichain-investigation-dashboard
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: multichain-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: django-trx-dashboard.onrender.com,.onrender.com,localhost,127.0.0.1
      - key: CORS_ALLOWED_ORIGINS
        value: https://django-trx-dashboard.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://django-trx-dashboard.onrender.com
    autoDeploy: false