# Generated by Django 4.2.7 on 2025-06-14 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactions", "0001_initial"),
        ("wallets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="wallets.wallet",
            ),
        ),
        migrations.AddIndex(
            model_name="pricecache",
            index=models.Index(
                fields=["symbol", "-last_updated"], name="transaction_symbol_0080d6_idx"
            ),
        ),
        migrations.AddField(
            model_name="portfoliocache",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["symbol", "chain"], name="transaction_symbol_acc174_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="asset",
            unique_together={("symbol", "chain")},
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["wallet", "-timestamp"], name="transaction_wallet__3e896f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type", "-timestamp"],
                name="transaction_transac_82ccd5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["asset_symbol", "-timestamp"],
                name="transaction_asset_s_a34786_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="portfoliocache",
            index=models.Index(
                fields=["user", "cache_key"], name="transaction_user_id_2aed8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portfoliocache",
            index=models.Index(
                fields=["expires_at"], name="transaction_expires_b017ea_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="portfoliocache",
            unique_together={("user", "cache_key")},
        ),
    ]
