# Generated by Django 4.2.7 on 2025-06-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0003_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="dark_theme",
            field=models.BooleanField(default=True),
        ),
    ]
