# Generated by Django 4.2.7 on 2025-06-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0005_remove_dark_theme_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="is_monitored",
            field=models.BooleanField(
                default=False, help_text="Enable real-time monitoring alerts"
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Investigation notes for this wallet"
            ),
        ),
    ]
