# Generated by Django 4.2.7 on 2025-06-17 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wallets", "0006_wallet_is_monitored_wallet_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("suspect", "Suspect"),
                            ("victim", "Victim"),
                            ("exchange", "Exchange"),
                            ("mixer", "Mixer"),
                            ("unknown", "Unknown"),
                            ("evidence", "Evidence"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("flagged", models.BooleanField(default=False)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="InvestigationCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "investigator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investigation_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallets",
                    models.ManyToManyField(
                        related_name="investigation_cases",
                        through="portfolio.CaseWallet",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="casewallet",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.investigationcase",
            ),
        ),
        migrations.AddField(
            model_name="casewallet",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wallets.wallet"
            ),
        ),
        migrations.AddIndex(
            model_name="investigationcase",
            index=models.Index(
                fields=["investigator", "status"], name="portfolio_i_investi_e3cba6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investigationcase",
            index=models.Index(
                fields=["status", "-updated_at"], name="portfolio_i_status_9afbea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casewallet",
            index=models.Index(
                fields=["case", "category"], name="portfolio_c_case_id_64ba4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casewallet",
            index=models.Index(
                fields=["flagged", "-added_at"], name="portfolio_c_flagged_be27aa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="casewallet",
            unique_together={("case", "wallet")},
        ),
    ]
