# Generated by Django 4.2.7 on 2025-06-17 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0006_wallet_is_monitored_wallet_notes"),
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casewallet",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_wallets",
                to="portfolio.investigationcase",
            ),
        ),
        migrations.AlterField(
            model_name="casewallet",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_wallets",
                to="wallets.wallet",
            ),
        ),
    ]
