# Generated by Django 4.2.7 on 2025-06-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                (
                    "chain",
                    models.CharField(
                        choices=[
                            ("ethereum", "Ethereum"),
                            ("solana", "Solana"),
                            ("bitcoin", "Bitcoin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contract_address", models.CharField(blank=True, max_length=100)),
                ("decimals", models.IntegerField(default=18)),
                (
                    "current_price_usd",
                    models.DecimalField(decimal_places=8, max_digits=20, null=True),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cache_key", models.CharField(max_length=100)),
                ("data", models.JSONField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PriceCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20, unique=True)),
                ("price_data", models.JSONField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tx_hash", models.CharField(max_length=100, unique=True)),
                ("block_number", models.BigIntegerField()),
                ("timestamp", models.DateTimeField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("buy", "Buy"),
                            ("sell", "Sell"),
                            ("transfer", "Transfer"),
                            ("contract_call", "Contract Call"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=18, max_digits=36)),
                ("asset_symbol", models.CharField(max_length=20)),
                ("asset_address", models.CharField(blank=True, max_length=100)),
                ("gas_fee", models.DecimalField(decimal_places=18, max_digits=36)),
                (
                    "usd_value",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
